#Data collection 
project_id: epoc
experiment_class: UniVie
base_data_dir: /data/jungfrau/instruments/jem2100plus
measurement_tag: Lysozyme
PI_name: Erik


#Detector configuration
nrows: 514
ncols: 1030
# detector:
#   det_id: 272
  
# plot: 
#  origin:  'lower'

# compute:
#   n_cores: 12

viewer_interval: 100
viewer_cmin: 0
viewer_cmax: 5e3


# Written to XDS template file
beam_center: [173, 170]

XDS_template: "/xtal/Integration/XDS/CCSA-templates/XDS-JUNGFRAU_50cm.INP"

# Overlays to be drawn in the GUI
overlays:
- {'type': 'circle', 'xy': [526, 253], 'radius': 188, 'ec': 'r', 'fill': False, 'lw': 2}
- {'type': 'circle', 'xy': [526, 253], 'radius': 5, 'ec': 'g', 'fill': False, 'lw': 2}
- {'type': 'rectangle', 'xy': [574, 52], 'width': 60, 'height': 31, 'angle': 27.5, 'ec': 'y', 'fill': False}
- {'type': 'rectangle', 'xy': [0, 0], 'width': 1000, 'height': 1, 'angle': 19.8, 'ec': 'r', 'fill': False}